---
sudo: false
dist: trusty
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - python3

services:
  - docker

env:
  global:
    - DOCKER_REPO=datawire/loom
    - secure: "Uqb0+1U8DFk41Jj+jvS0W+DHhH0qnbnl+mpeOjPRz5+nj4yXyKxcDHOWlNHTv0zhf/0Caf5ENtJh/tww1xy8OZZtof58WYVlMtmYPC+e0MmKLBLFrwfxY3fa2yYXohT+eXrzW/JPhrIqgbVAmlpNNDFbW4sBb/QNkVA7wukvvYEHi8wrUHx4LJIbzXfhT3o8BUUJobK+QYvRCmzgr9AtWhyn7F7myvC/jkli9C8b9/QKx+for0p6zxWK6l5QSxj1eoxRt8CGSkr0rbx6LC/5O81lpNIJSvS3F7vom1Qor4AlDHxxxtJJ3qe/Q6efIBFBsmabFb+KO33m+tpmCOaHvCaNEckDCd5/OFPz/h0eE84tJxUn5g/MU2bDWjA46PX2iyeITln+2YNofkbdbyOajE61EpYSny6LMyA5rIwqEjnNtB5rqhCNw7gj+xkDuZ3WuBT9CzXhTx+p6RTdroSusU/MFQhrwGMoB7Ef2aBWHuPNf0vconitn3OtwRm1DA1QpoAQ177DeeUgQ9/qf1fV5ilk/i+BamA59pVN0EMEGTn+MC0RYPwMlWfGnQmYmI9AcAycmneauEOfrg/sZDwgFWNCcsoN06+9hnY2Um2D7fb6nmjg1t2j/OdCjDKdX/nD6vA9MHPpB8TDUtvqIId7ZaXAnEb2wgRWC3qaudOrR+s="
    - secure: "iScIlWauLe07kBmMg4WL7dIB3hKZsKthatc37SK9tGWzG6/sN3GzvpcHr/uYp2PfLq/1o8BVQZiNA+VpN8srwn90FFsMT1uI/25nPHlSIpE4Tw7MFt+zo2QlTqiM4FrgpQf1gYYNjHXUPu1156p++nBh2GlkcP3SO57ttav5u5rkXhB0jVknDb4znpia7mz3g0+5OJ1FgoRAo6X7C9X7ZhICkFzE95s7T2C2bSScV4N7RQL9SqMeQTUACj0TlLXxOlfYJuaf8uV1Z5dqv8zFfMt4nDZCcvwApk5JfA3Q7FNmUmIjAVgJfIa+eNTjklGWsqPX24ZUyAAeQh1BN6vDUOW5lsDpPnFXc+iZWjRksL6hyjpCip3NfKAnyThZzs3UjbyKw3n3ddjD4dS/ZSHSz3gMUDB3tynOcgwa1CidiHhFdCB9aSQeUIPm1DkFkuHwJg2XitjH77O/cwL80OvBAZe/MI6TVrjBwIq+3y/7cjXzf+sIytQhQm/Hk6TFOrV1GrUIpAXszYVKhZtZnderGqgQ4myQyS00jJsoDVvn/+xgcyi0ubc/scuTA5NWvslx9WES4qHrDdc+vNrfd8U+E+3Kels7A+NPn8U8mU7R4PtF/CXPJpr9EaKRv+PtXMXnwW37ljyBeAV1D2dD3Bmj/M4rpYu8jFYkqzBFFaHzvpk="
    - COMMIT=${TRAVIS_COMMIT::8}
    - PACKER_VERSION=1.0.0

before_script:
  - bash ci/travis_before_script.sh

script:
  - bash ci/travis_script.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/