title: Loom
email: hello@datawire.io
author: "Datawire.io"
description: "Loom: Self-service provisioning for microservices in Kubernetes"
keywords: "Loom, provisioning, Kubernetes, microservices"

baseurl: ""
url: "http://loom.run" # the base hostname & protocol for your site
twitter_username: datawire
github_username:  datawire

# use this to define the categories of your documentation
category-list:
  - "about"
  - "getting-started"
  - "user-guide"
  - "additional-information"

# optionally you can define icon for each category (for the sidebar)
# Doc42 uses Font Awesome
category-icons: [question-circle, play, code, expand]

# Build settings
markdown: kramdown
