package io.datawire.loom.fabric


enum class FabricStatus {
    NOT_STARTED,
    NETWORKING_CREATION_STARTED,
    NETWORKING_CREATION_COMPLETED,
    KUBERNETES_CREATION_STARTED,
    KUBERNETES_CREATION_COMPLETED,
    FAILED,
    SUCCEEDED
}